### ISSUE TITLE
responsive-loader with sharp error

### ISSUE THREAD

**Issue by Qeneke** [cyrilwanner/next-optimized-images#50]
I get this error when I use the responsive-loader with sharp, but it works well with the jimp module.

> Error: Cannot find module '...node_modules\responsive-loader\lib\index.js/sharp'

-Windows OS

**Comment by cyrilwanner** [comment]
Hi @Qeneke 	
Thank you for reporting this issue! This was my bad, I didn't think about the different directory separator on windows when I wrote the regex for detecting the sharp adapter.
I just published v2.3.1 to npm which should solve this issue.

**Comment by vioule** [comment]
Got the same error 
`Error: Cannot find module '.../node_modules/responsive-loader/lib/cjs.js/sharp'`

```
package.json
  "dependencies": {
    "imagemin-mozjpeg": "^9.0.0",
    "next": "9.5.1",
    "next-optimized-images": "^2.6.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "responsive-loader": "^2.0.2",
    "sharp": "^0.25.4",
    "styled-components": "^5.1.1"
  },
```

I solved the problem like this for the moment in responsive-loader.js

```
  if (!adapter && detectedLoaders.responsiveAdapter === 'sharp') {
    console.log('wrong :')
    console.log(`${detectedLoaders.responsive}${path.sep}sharp`)
    console.log('right :')
    console.log(`${detectedLoaders.responsive.split('lib')[0]}sharp`)
    // adapter = require(`${detectedLoaders.responsive}${path.sep}sharp`); // <-- old one
    adapter = require(`${detectedLoaders.responsive.split('lib')[0]}sharp`); // <-- new one
  }
```

wrong :
../node_modules/responsive-loader/lib/cjs.js/sharp
right :
../node_modules/responsive-loader/sharp

**Comment by 7mioda** [comment]
I got the same error Error: Cannot find module '.../node_modules/responsive-loader/lib/cjs.js/sharp'

**Comment by traversng** [comment]
Im still getting this error with version: 2.6.2. Can we reopen this issue?

**Comment by alexis-regnaud** [comment]
Same for me. Work with 2.0.0 but not for 2.0.1 and 2.0.2

**Comment by hayanisaid** [comment]
I'm having the same issue 😩

**Comment by Kaveri-Pradhan** [comment]
Same issue on Mac

**Comment by nur557** [comment]
Same issue.

**Comment by Germs31** [comment]
Same Issue

**Comment by mrroll** [comment]
I've made a [PR](https://github.com/cyrilwanner/next-optimized-images/pull/201) and a [temporary package](https://www.npmjs.com/package/@mrroll/next-optimized-images)

**Comment by AdsonCicilioti** [comment]
Same problem.

**Comment by AdriaN458** [comment]
For anyone still having this issue, downgrade the package to 2.0.0 for now. Hopefully, it'll be fixed for newer versions.

`npm i responsive-loader@2.0.0`

**Comment by jjaburke91** [comment]
I found adding the adapter property to the responsive loader options resolved the error, instead of having to revert to v2.0.0.

Following information found in the responsive loader docs, saying you need to specify the sharp loader: https://github.com/dazuaz/responsive-loader#with-sharp

```
module.exports = withPlugins([
    [optimizedImages, {
        responsive: {
            adapter: require('responsive-loader/sharp')
        }
        ...
    }],
]);

**Comment by jrhager84** [comment]
Any word on a fix for this?

**Comment by JohannesSchwegler** [comment]
> For anyone still having this issue, downgrade the package to 2.0.0 for now. Hopefully, it'll be fixed for newer versions.
> 
> `npm i responsive-loader@2.0.0`

Unfortunately, this is not working for me. Using it with nuxt-optimized-images

**Comment by toviszsolt** [comment]
version: `"responsive-loader": "^2.3.0"`
result: `Error: Cannot find module '...\node_modules\responsive-loader\lib\cjs.js\sharp`

**Comment by barclayiversen** [comment]
Having this issue, still no fix?

**Comment by ojoven** [comment]
Wow! It's been a long ride!
Same here, same error.

**Comment by ojoven** [comment]
Hey everyone, I didn't try it but I found this on responsive-loader's npm:
https://www.npmjs.com/package/responsive-loader

_If you want to use sharp, you need to configure responsive-loader to use its adapter:_
```
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.(jpe?g|png|webp)$/i,
        use: [
          loader: 'responsive-loader',
          options: {
            adapter: require('responsive-loader/sharp')
          }
        ]
      }
    ]
  },
}
```

Not gonna lie, I went for Jimp, but I thought this could help.

**Comment by Msulecki** [comment]
> Not gonna lie, I went for Jimp, but I thought this could help.

Defining Sharp as adapter in config worked for me, thanks

**Comment by FaCRO** [comment]
Adding 
```
  responsive: {
    adapter: require("responsive-loader/sharp"),
  },
```
to the nextjs config should help, following the implementation at https://github.com/cyrilwanner/next-optimized-images/blob/fe31e5c77008a88ce9ffe76d504229562ad8a549/lib/loaders/responsive-loader.js#L15
